default_install_hook_types:
  - pre-commit
  - post-merge

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.5
    hooks:
      - id: uv-sync
      - id: uv-lock
      - id: uv-export
        args: [--no-hashes, --output-file=requirements.txt]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD013, --disable=MD033]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--extend-select=I, --fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty-check
        name: ty-check
        language: python
        entry: ty check
        pass_filenames: false
        args: [--python=.venv/]
        additional_dependencies: [ty]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: [prettier]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.27.0
    hooks:
      - id: eslint
        args: [--fix, --config, extension/eslint.config.js]
        additional_dependencies: [eslint]
