services:
  - type: web
    name: filtergenie-api
    plan: free

    # Source code information
    repo: https://github.com/daltunay/filtergenie
    runtime: docker
    dockerfilePath: ./Dockerfile

    # Deployment configuration
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /health

    # Environment variables
    envVars:
      - key: API_KEY
        generateValue: true
      - key: API_PROFILE
        value: true
      - key: CACHE_ENABLED
        value: true
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL_NAME
        value: meta-llama/llama-4-scout-17b-16e-instruct

    # Build configuration
    buildFilter:
      paths:
        - backend/**
        - render.yaml
        - Dockerfile
        - .dockerignore
        - uv.lock
        - .python-version
      ignoredPaths:
        - backend/tests/**
