services:
  - type: web
    name: filtergenie-api
    plan: free

    # Source code information
    repo: https://github.com/daltunay/filtergenie
    runtime: docker
    dockerfilePath: ./Dockerfile

    # Deployment configuration
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /health

    # Environment variables
    envVars:
      - key: MODEL__REMOTE__API_KEY
        sync: false
      - key: API__KEY
        generateValue: true

    # Build configuration
    buildFilter:
      paths:
        - backend/**
        - render.yaml
