name: build-extension
permissions:
  contents: read

on:
  workflow_call:
  release:
    types: [published]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if build-relevant files changed
        id: check_diff
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -Eq '^extension/'
        continue-on-error: true

      - name: Set up Node.js
        if: steps.check_diff.outcome == 'success'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        if: steps.check_diff.outcome == 'success'
        run: npm install
        working-directory: extension

      - name: Run npm build
        if: steps.check_diff.outcome == 'success'
        run: npm run build
        working-directory: extension

      - name: Zip extension
        if: steps.check_diff.outcome == 'success'
        run: |
          cd extension
          zip -r ../extension.zip .

      - name: Upload extension artifact
        if: steps.check_diff.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.zip

  upload-release-asset:
    needs: build-extension
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
