name: ci
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  run-tests:
    uses: ./.github/workflows/run-tests.yml
  npm-build:
    uses: ./.github/workflows/npm-build.yml
