name: ci
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  run-tests:
    needs: pre-commit
    uses: ./.github/workflows/run-tests.yml
  build-extension:
    needs: run-tests
    uses: ./.github/workflows/build-extension.yml
