name: CI
permissions:
  contents: read
  actions: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Python dependencies
        run: uv sync --locked --dev
        env:
          UV_PROJECT_ENVIRONMENT: .venv

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm install
        working-directory: extension

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  run-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Python dependencies (with local extra)
        run: uv sync --locked --dev --extra local
        env:
          UV_PROJECT_ENVIRONMENT: .venv

      - name: Run pytest
        run: uv run pytest --cov=backend
        env:
          MODEL__REMOTE__API_KEY: dummy-key

  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm install
        working-directory: extension

      - name: Run npm build
        run: npm run build
        working-directory: extension

      - name: Zip extension
        run: |
          cd extension
          zip -r ../extension.zip .

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.zip
