name: release-extension
permissions:
  contents: write
  actions: read

on:
  release:
    types: [published]

jobs:
  build-extension:
    name: Build and Zip Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm install
        working-directory: extension

      - name: Run npm build
        run: npm run build
        working-directory: extension

      - name: Zip extension
        run: |
          cd extension
          zip -r ../extension.zip \
            manifest.json \
            dist \
            assets \
            popup \
            utils \
            platforms \
            src

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.zip

  upload-release-asset:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: build-extension
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
