name: release-extension
permissions:
  contents: write
  actions: read

on:
  release:
    types: [published]

jobs:
  upload-release-asset:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
