name: update-badge
on:
  workflow_run:
    workflows: ["pre-commit"]
    types:
      - completed
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: bash scripts/update_badge.sh

      - name: Update Badge
        run: |
          new_url=$(cat badge-url.txt)
          sed -i "s|https://img.shields.io/badge/Render-[^?]*?logo=render&style=for-the-badge|$new_url|" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "[skip render] update badge" && git push
