name: update-badge
permissions:
  contents: write

on:
  deployment_status:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Render Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: bash scripts/render_badge.sh

      - name: Generate Deployment Badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/deployment_badge.sh

      - name: Update badges in README
        run: |
          render_url=$(cat render-badge-url.txt)
          deployment_url=$(cat deployment-badge-url.txt)
          sed -i "s|![Render Status](https://img.shields.io/badge/Render-[^?)]*?logo=render&style=for-the-badge)|![Render Status]($render_url)|" README.md
          sed -i "s|![Deployment Status](https://img.shields.io/badge/GitHub-[^?)]*?logo=github&style=for-the-badge)|![Deployment Status]($deployment_url)|" README.md

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          if ! git diff --quiet README.md; then
            git commit -am "[skip render] update badge"
            git push
          fi
