name: update-badge
permissions:
  contents: write

on: deployment_status

jobs:
  update-badge:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: bash scripts/generate_badge.sh

      - name: Update badge
        run: |
          new_url=$(cat badge-url.txt)
          sed -i "s|https://img.shields.io/badge/Render-[^?]*?logo=render&style=for-the-badge|$new_url|" README.md

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          if ! git diff --quiet README.md; then
            git commit -am "[skip render] update badge"
            git push
          fi
