name: update-badge
on:
  workflow_run:
    workflows: ["pre-commit"]
    types:
      - completed
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: npx render-status-badge >> badge-url.txt

      - name: Update Badge
        run: |
          sed -i "s|https://img.shields.io/badge/Render-Unknown-lightgrey?logo=render
          git commit -am "[skip render] update badge" && git push
