name: update-badges
permissions:
  contents: write

on:
  deployment_status:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-render-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: bash scripts/render_badge.sh

      - name: Update badge in README
        run: |
          render_url=$(cat render-badge-url.txt)
          sed -i "s|![Render Status](https://img.shields.io/badge/render-[^?)]*\?logo=render&style=for-the-badge)|![Render Status]($render_url)|" README.md
          echo "=== README diff after sed ==="
          git --no-pager diff README.md || true

      - name: Commit and push badge update
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          if ! git diff --quiet README.md; then
            git commit -am "[skip render] update render badge"
            git push
          fi

  update-deployment-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/deployment_badge.sh

      - name: Update badge in README
        run: |
          deployment_url=$(cat deployment-badge-url.txt)
          sed -i "s|![Deployment Status](https://img.shields.io/badge/deployment-[^?)]*\?logo=github&style=for-the-badge)|![Deployment Status]($deployment_url)|" README.md
          echo "=== README diff after sed ==="
          git --no-pager diff README.md || true

      - name: Commit and push badge update
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          if ! git diff --quiet README.md; then
            git commit -am "[skip render] update deployment badge"
            git push
          fi
